[project]
name = "agenticai"
version = "0.1.0"
description = "My First Agentic AI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "phidata",
    "duckduckgo-search",
    "groq",
    "yfinance",
]
